stamp:
  type: LSST_Silicon
  det_name: "$det_name"
  world_pos:
    type: InstCatWorldPos
  draw_method: phot
  photon_ops:
    -
      type: PupilAnnulusSampler
      R_inner: 2.55
      R_outer: 4.18
    -
      type: TimeSampler
    -
      type: RubinOptics
      camera: "@output.camera"
      boresight: $boresight
      det_name: $det_name
